version: '3.7'
services:
  postgres:
    image: postgres:15.1
    env_file: [ .env ]
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "9000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gpt-proxy:
    env_file: [ .env ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9001:8000'
